### ISSUE TITLE
Can't install requirements

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-ros#3]
Hello @inetuid,
looks like requirements can't be installed:

```
(napalm) ➜  napalm-ros git:(develop) ✗ pip install -r requirements.txt
Collecting napalm-base (from -r requirements.txt (line 1))
Collecting yandc (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement yandc (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for yandc (from -r requirements.txt (line 2))
```

I saw that yandc is a library you have on your own account, you should make it installable and, optionally, publish it on pip.

**Comment by dbarrosop** [comment]
It's also interesting to note that I was checking `yandc` and it looks like a similar idea to napalm. The only comment I might make about using that library instead of just directly whatever library mikrotic might provide is that we have to be careful we don't introduce too many unnecessary requirements

**Comment by inetuid** [comment]
Yeah, it's something I mentioned on the initial mail to the napalm-automation group as needing to be looked at. The yandc library was my first decent sized Python project and was based on a previous Perl module that performed the same functionality.

Once I'd done the conversion, I ended up looking around for similar things which is how I came across Napalm 8-) It then seemed like a good idea to see if I could layer the Napalm methods on top of the library more of a unit test of my library than anything else. It got to the stage where I'd implemented so much that it seemed work sharing with a wider community - hence how we got here.

I'm planning to commit some changes over the next few days that split some of the Mikrotik ROS specifics so that Napalm won't have to depend on the whole of my library. This will be the first stage to getting rid of it as a dependency.

**Comment by inetuid** [comment]
Oh, and I'm working though getting it on PyPI so it's instalable.

**Comment by dbarrosop** [comment]
That sounds great! Once that works I will keep testing and reviewing : )

It would also be nice if you could help me getting access to a microtik device for testing, I don't care if it's virtual or real as long as I can run some tests.

**Comment by mirceaulinic** [comment]
Wouldn't be easier to move the code that manager the connection from your lib (which is pretty small) into napalm-ros?
It would also be cleaner and would respect the standard of the other drivers - anyway you are using the ros API, don't you?

**Comment by inetuid** [comment]
There should now have a working version of the library on PyPI that can be installed via pip.

A test instance (Vagrant box) is next on my TODO list - taking longer than expected due to learning curve of github, unittest, PyPI and now Vagrant. Thanks to @dbarrosop there is at least a useful crib sheet on creating a box online 8-)

At present the transport used is SSH and screen scraping (albeit the device can output in a 'machine readable' format). On the TODO list to make use of the API instead...

**Comment by inetuid** [comment]
Apologies for the time it's taken for this, but I've created a Vagrant box that works on my own test setup. Not sure how these should be distributed - currently it's available here - https://drive.google.com/file/d/0Bz_mygUBVsceNTBTVmNobmVQdkE/view?usp=sharing
